<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Working Class Representative Performance</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">TEAM NAME</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./proposal.html">Proposal</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./presentation.pdf">Presentation</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./report.html" aria-current="page">Report</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html">About</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction-and-data" id="toc-introduction-and-data" class="nav-link active" data-scroll-target="#introduction-and-data"><strong>Introduction and Data</strong></a></li>
  <li><a href="#literature" id="toc-literature" class="nav-link" data-scroll-target="#literature"><strong>Literature</strong></a></li>
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology"><strong>Methodology</strong></a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><strong>Results</strong></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Working Class Representative Performance</h1>
<p class="subtitle lead">Which factors positively contribute to votes in their favor</p>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="introduction-and-data" class="level1">
<h1><strong>Introduction and Data</strong></h1>
<p>The data set came from a journal published at Political Research Quarterly (2023). The authors were Eric Hansen, who is the assistant professor of political science at Loyola University Chicago and Sarah A. Treul, an Associate Professor of political science at UNC.</p>
<p>The authors collected, recorded, and analyzed novel data describing the occupational background of all candidates who competed in the U.S. House primaries between 2008 and 2016.</p>
<p>The dataset was used to give us an idea of how well candidates perform in U.S. House primary elections. In total, there are 7869 observations and 24 variables. Each observation represents a candidate who competed in the U.S. Hour primaries between 2008 and 2016. Each row of observation included a variety of factors related to election results, such as vote share, fundraising, incumbency status, education level, ideology, number of opponents, and political affiliation. Not all variables are useful in terms of predicting the candidate’s performance as some of them are only numerical descriptions of vote share.</p>
<p>This research question is important for the following reasons. Given that the working class is less represented among high-level elected government officials, we would like to encourage research dedicated to this issue in order to identify factors that contribute to this phenomenon. Research in this area has focused on the barriers hindering working-class representatives. As a result, we do not know much about what factors allow working-class elected officials to overcome these barriers to election and thus, what factors influence their positive performance. We have decided to focus our research on working-class officials who have been elected to office as a case study. Results from our research would provide valuable insight to future working-class candidates. Ultimately, we hope this project can provide insight to future working class candidates providing more guidance to their campaign strategies and fundraising efforts. As a result, we hope this could contribute to more equality and equity in the government.</p>
</section>
<section id="literature" class="level1">
<h1><strong>Literature</strong></h1>
<p><strong>Primary Barriers to Working Class Representation</strong></p>
<p>Treul, S. A., &amp; Hansen, E. R. (2023). Primary Barriers to Working Class Representation. Political Research Quarterly, 0(0). https://doi.org/10.1177/10659129231154914</p>
<p>This research article is written by Sarah Treul who co-published the dataset Primary Barriers to Working Class Representation which we hope to utilize in our research. Her research seeks to answer how working class candidates fare in primary elections given that working class candidates are a minority on the ballot compared to white-collar candidates. The research article analyzed occupational backgrounds of primary election candidates for the U.S. House of Representatives from 2008 to 2016 with election results. Treul et al.&nbsp;found that from 2008 to 2016, working class candidates are 31% less likely to win elections and tend to score 24% less votes than white collar candidates. In their analysis, Treul et al.&nbsp;suggests that lower success in primary elections for the working class may be due lower funding and negative bias among party leaders towards working class candidates.&nbsp;</p>
<p>This article uses the Primary Barriers to Working Class Representation dataset to analyze election results based on whether the candidates were working class and then analyzes factors that affected why working class candidates did not win elections. Our research would seek to understand how working class candidates overcame barriers to winning primary elections by analyzing factors that were outliers among candidates that did win the election.&nbsp;</p>
</section>
<section id="methodology" class="level1">
<h1><strong>Methodology</strong></h1>
<p><strong><em>Variables Selection:</em></strong></p>
<ol type="1">
<li><p>Dependent variable: <strong>candpct</strong>, which represents the candidate’s vote share in the primary election.</p></li>
<li><p>Independent variables: We select the variables that potentially measure factors related to the candidate’s vote share. These selected 14 independent variables include:</p></li>
</ol>
<ul>
<li><p>state_abbrev (the state the candidate is from)</p></li>
<li><p>candnumber (count of opponents in the candidate’s primary election)</p></li>
<li><p>cand_party (the party of the candidate)</p></li>
<li><p>quality_cand (0=candidate is nonquality nonincumbent, 1=candidate is quality nonincumbent, 2=candidate is incumbent)</p></li>
<li><p>qualnumber (count of quality opponents)</p></li>
<li><p>openseat (whether the incumbent is running for reelection)</p></li>
<li><p>partyDonors1 (count of donations candidate received from donors to their party’s national campaign funds)</p></li>
<li><p>college (percentage of the congressional district’s residents who hold four-year college degrees)</p></li>
<li><p>dist_income (median income of the congressional district)</p></li>
<li><p>total_primary (total dollars contributed toward a candidate’s campaign funds and outside spending, unit: millions of dollars)</p></li>
<li><p>third (whether candidate runs as a third party or independent)</p></li>
<li><p>gop (whether the candidate is Republican)</p></li>
<li><p>ideo_extreme (absolute value of Bonica’s CFscore measure of candidate ideology)</p></li>
<li><p>former_worker (whether the candidate used to be a worker but is no longer now)</p></li>
</ul>
<p><strong><em>Analysis Procedure:</em></strong></p>
<ol type="1">
<li><p>First, we filter the dataset and keep only candidates with working-class background (worker == 1) and have won the election (winwin == 1).</p></li>
<li><p>Second, we use the forward and backward model selection method to compare and choose the variables that best predict the dependent variable. Specifically, for the forward selection, we first try to fit each variable in a linear regression model with a single independent variable and find out which fits the best (the one with the lowest AIC). Then, we try to add each variable into the existing best model, and find out the best. Theoretically, we repeat this process by trying to add more variables and compare the AIC until we find out the best model. But since the number of variables is too large, we use the stepAIC method in R to perform the forward model selection. To see which model selection methods work better and generate more useful results, we also use the stepAIC method to perform the backward model selection. Based on the results, we select the model with the lowest AIC and conclude the most prominent factors related to the vote share as well as the coefficients of the factors.</p></li>
<li><p>Then, using the factors selected, we also run an interactive multiple linear regression model to see which of the additive and interactive model works better. Based on the results, we select the model with the lower AIC.</p></li>
<li><p>Lastly, to get make the results more straightforward and readable, we visualize the results by&nbsp;[Note: we are confused about this part and we left a comment at the end of the Results section. We might need some help with this part, thanks!]</p></li>
</ol>
</section>
<section id="results" class="level1">
<h1><strong>Results</strong></h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>candidate <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"data/Treul_Hansen_Replication_Data.tab"</span>, </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">sep =</span> <span class="st">"</span><span class="sc">\t</span><span class="st">"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(candidate, <span class="at">file =</span> <span class="st">"data/candidate.csv"</span>, <span class="at">col.names =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in write.csv(candidate, file = "data/candidate.csv", col.names = TRUE):
attempt to set 'col.names' ignored</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(candidate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 7,869
Columns: 24
$ worker                &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, …
$ worker_current_recode &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ state_abbrev          &lt;chr&gt; "IN", "WA", "NH", "MI", "MD", "MN", "TN", "WV", …
$ raceid                &lt;int&gt; 201014091, 200847089, 201029010, 201222021, 2010…
$ year                  &lt;int&gt; 2010, 2008, 2010, 2012, 2010, 2016, 2014, 2008, …
$ dem_vote              &lt;dbl&gt; 0.4470, 0.4720, 0.4400, 0.3590, 0.6500, 0.3427, …
$ candnumber            &lt;int&gt; 5, 6, 8, 1, 3, 3, 4, 1, 5, 3, 3, 6, 2, 2, 7, 1, …
$ cand_party            &lt;chr&gt; "Democrat", "Third-Party", "Republican", "Democr…
$ candvotes             &lt;int&gt; 4820, 2116, 653, 1, 5479, 4402, 4434, 15919, 343…
$ tvotes                &lt;int&gt; 54552, 152726, 65283, 1, 53352, 9566, 30183, 159…
$ candpct               &lt;dbl&gt; 0.088356100, 0.013854877, 0.010002600, 1.0000000…
$ winwin                &lt;int&gt; 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, …
$ quality_cand          &lt;int&gt; 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ qualnumber            &lt;int&gt; 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 2, 0, …
$ openseat              &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, …
$ PartyDonors1          &lt;int&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ college               &lt;dbl&gt; 0.1172, 0.2649, 0.2080, 0.1564, 0.1818, 0.2096, …
$ dist_income           &lt;dbl&gt; 0.42314, 0.82671, 0.61948, 0.46584, 0.83020, 0.7…
$ total_primary         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, NA, 0, 0, NA, 0, 0, 0, 0, 0, 0…
$ third                 &lt;dbl&gt; 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, …
$ gop                   &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, …
$ ideo_extreme          &lt;dbl&gt; NA, NA, NA, NA, 1.119, NA, NA, NA, NA, NA, NA, N…
$ qualbin               &lt;dbl&gt; 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ former_worker         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, …</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>candidate_won <span class="ot">&lt;-</span> candidate <span class="sc">|&gt;</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(winwin <span class="sc">==</span> <span class="dv">1</span>, worker <span class="sc">==</span> <span class="dv">1</span>) <span class="co">#337 observations</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>candidate_won_new <span class="ot">&lt;-</span> candidate_won[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">9</span>, <span class="dv">10</span>, <span class="dv">22</span>, <span class="dv">23</span>)]</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>candidate_final <span class="ot">&lt;-</span> candidate_won_new <span class="sc">|&gt;</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>candidate_final <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nrow</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 312</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>lm1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(candpct <span class="sc">~</span> state_abbrev <span class="sc">+</span> candnumber <span class="sc">+</span> cand_party <span class="sc">+</span> quality_cand</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>          <span class="sc">+</span> qualnumber <span class="sc">+</span> openseat <span class="sc">+</span> PartyDonors1 <span class="sc">+</span> college <span class="sc">+</span> dist_income</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>          <span class="sc">+</span> total_primary <span class="sc">+</span> third <span class="sc">+</span> gop <span class="sc">+</span> former_worker, </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> candidate_final)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">stepAIC</span>(lm1,  <span class="at">direction =</span> <span class="st">"backward"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=-1216.6
candpct ~ state_abbrev + candnumber + cand_party + quality_cand + 
    qualnumber + openseat + PartyDonors1 + college + dist_income + 
    total_primary + third + gop + former_worker


Step:  AIC=-1216.6
candpct ~ state_abbrev + candnumber + cand_party + quality_cand + 
    qualnumber + openseat + PartyDonors1 + college + dist_income + 
    total_primary + third + former_worker


Step:  AIC=-1216.6
candpct ~ state_abbrev + candnumber + cand_party + quality_cand + 
    qualnumber + openseat + PartyDonors1 + college + dist_income + 
    total_primary + former_worker

                Df Sum of Sq    RSS     AIC
- state_abbrev  37    0.9420 5.5877 -1233.0
- cand_party     1    0.0001 4.6458 -1218.6
- college        1    0.0016 4.6473 -1218.5
- former_worker  1    0.0157 4.6614 -1217.5
&lt;none&gt;                       4.6457 -1216.6
- dist_income    1    0.0448 4.6905 -1215.6
- total_primary  1    0.0478 4.6935 -1215.4
- PartyDonors1   1    0.0490 4.6947 -1215.3
- openseat       1    0.0500 4.6956 -1215.3
- qualnumber     1    0.1728 4.8185 -1207.2
- quality_cand   1    0.3997 5.0454 -1192.8
- candnumber     1    3.3753 8.0209 -1048.2

Step:  AIC=-1233
candpct ~ candnumber + cand_party + quality_cand + qualnumber + 
    openseat + PartyDonors1 + college + dist_income + total_primary + 
    former_worker

                Df Sum of Sq     RSS     AIC
- cand_party     1    0.0001  5.5878 -1235.0
- college        1    0.0187  5.6064 -1234.0
- former_worker  1    0.0267  5.6144 -1233.5
- PartyDonors1   1    0.0270  5.6147 -1233.5
&lt;none&gt;                        5.5877 -1233.0
- openseat       1    0.0549  5.6426 -1232.0
- dist_income    1    0.1026  5.6903 -1229.3
- total_primary  1    0.1446  5.7323 -1227.0
- qualnumber     1    0.2674  5.8551 -1220.4
- quality_cand   1    0.6903  6.2780 -1198.7
- candnumber     1    5.2843 10.8720 -1027.3

Step:  AIC=-1234.99
candpct ~ candnumber + quality_cand + qualnumber + openseat + 
    PartyDonors1 + college + dist_income + total_primary + former_worker

                Df Sum of Sq     RSS     AIC
- college        1    0.0187  5.6065 -1236.0
- former_worker  1    0.0268  5.6146 -1235.5
- PartyDonors1   1    0.0269  5.6147 -1235.5
&lt;none&gt;                        5.5878 -1235.0
- openseat       1    0.0553  5.6431 -1233.9
- dist_income    1    0.1038  5.6916 -1231.2
- total_primary  1    0.1446  5.7324 -1229.0
- qualnumber     1    0.2690  5.8568 -1222.3
- quality_cand   1    0.6916  6.2794 -1200.6
- candnumber     1    5.3842 10.9720 -1026.5

Step:  AIC=-1235.95
candpct ~ candnumber + quality_cand + qualnumber + openseat + 
    PartyDonors1 + dist_income + total_primary + former_worker

                Df Sum of Sq     RSS     AIC
- former_worker  1    0.0286  5.6351 -1236.4
- PartyDonors1   1    0.0314  5.6378 -1236.2
&lt;none&gt;                        5.6065 -1236.0
- openseat       1    0.0526  5.6591 -1235.0
- dist_income    1    0.1205  5.7270 -1231.3
- total_primary  1    0.1398  5.7463 -1230.3
- qualnumber     1    0.2608  5.8673 -1223.8
- quality_cand   1    0.6746  6.2811 -1202.5
- candnumber     1    5.4270 11.0335 -1026.7

Step:  AIC=-1236.37
candpct ~ candnumber + quality_cand + qualnumber + openseat + 
    PartyDonors1 + dist_income + total_primary

                Df Sum of Sq     RSS     AIC
- PartyDonors1   1    0.0316  5.6667 -1236.6
&lt;none&gt;                        5.6351 -1236.4
- openseat       1    0.0566  5.6917 -1235.2
- dist_income    1    0.1286  5.7636 -1231.3
- total_primary  1    0.1560  5.7911 -1229.8
- qualnumber     1    0.2627  5.8977 -1224.2
- quality_cand   1    0.8550  6.4901 -1194.3
- candnumber     1    5.4582 11.0932 -1027.0

Step:  AIC=-1236.62
candpct ~ candnumber + quality_cand + qualnumber + openseat + 
    dist_income + total_primary

                Df Sum of Sq     RSS     AIC
&lt;none&gt;                        5.6667 -1236.6
- openseat       1    0.0505  5.7172 -1235.8
- dist_income    1    0.1114  5.7781 -1232.5
- total_primary  1    0.1895  5.8562 -1228.4
- qualnumber     1    0.2988  5.9655 -1222.6
- quality_cand   1    1.2017  6.8684 -1178.6
- candnumber     1    5.4504 11.1171 -1028.4</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = candpct ~ candnumber + quality_cand + qualnumber + 
    openseat + dist_income + total_primary, data = candidate_final)

Coefficients:
  (Intercept)     candnumber   quality_cand     qualnumber       openseat  
      0.99127       -0.10978        0.08668       -0.05079        0.05474  
  dist_income  total_primary  
     -0.14245        0.15614  </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>lm2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(candpct <span class="sc">~</span> state_abbrev, <span class="at">data =</span> candidate_final)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stepAIC</span>(lm2,  <span class="at">scope =</span> <span class="sc">~</span> state_abbrev <span class="sc">+</span> candnumber <span class="sc">+</span> cand_party <span class="sc">+</span> quality_cand</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>          <span class="sc">+</span> qualnumber <span class="sc">+</span> openseat <span class="sc">+</span> PartyDonors1 <span class="sc">+</span> college <span class="sc">+</span> dist_income</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>          <span class="sc">+</span> total_primary <span class="sc">+</span> third <span class="sc">+</span> gop <span class="sc">+</span> former_worker,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">direction =</span> <span class="st">"forward"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=-919.93
candpct ~ state_abbrev

                Df Sum of Sq     RSS      AIC
+ candnumber     1    7.0298  5.7892 -1165.95
+ qualnumber     1    3.0725  9.7464 -1003.42
+ quality_cand   1    1.0790 11.7399  -945.36
+ total_primary  1    0.6870 12.1319  -935.12
+ openseat       1    0.5464 12.2725  -931.52
+ college        1    0.4283 12.3907  -928.53
+ cand_party     1    0.4154 12.4036  -928.21
+ gop            1    0.4154 12.4036  -928.21
+ dist_income    1    0.3945 12.4244  -927.68
+ former_worker  1    0.2506 12.5684  -924.09
+ PartyDonors1   1    0.1835 12.6354  -922.43
&lt;none&gt;                       12.8190  -919.93

Step:  AIC=-1165.95
candpct ~ state_abbrev + candnumber

                Df Sum of Sq    RSS     AIC
+ quality_cand   1   0.64341 5.1458 -1200.7
+ PartyDonors1   1   0.32251 5.4667 -1181.8
+ former_worker  1   0.23521 5.5540 -1176.9
+ dist_income    1   0.11709 5.6721 -1170.3
+ college        1   0.07691 5.7123 -1168.1
+ qualnumber     1   0.04488 5.7443 -1166.4
&lt;none&gt;                       5.7892 -1166.0
+ total_primary  1   0.02896 5.7602 -1165.5
+ cand_party     1   0.02400 5.7652 -1165.2
+ gop            1   0.02400 5.7652 -1165.2
+ openseat       1   0.02174 5.7674 -1165.1

Step:  AIC=-1200.71
candpct ~ state_abbrev + candnumber + quality_cand

                Df Sum of Sq    RSS     AIC
+ qualnumber     1  0.158993 4.9868 -1208.5
+ total_primary  1  0.086519 5.0593 -1204.0
+ openseat       1  0.077950 5.0678 -1203.5
+ PartyDonors1   1  0.072241 5.0735 -1203.1
+ dist_income    1  0.059072 5.0867 -1202.3
+ former_worker  1  0.046199 5.0996 -1201.5
&lt;none&gt;                       5.1458 -1200.7
+ college        1  0.031269 5.1145 -1200.6
+ cand_party     1  0.027321 5.1184 -1200.4
+ gop            1  0.027321 5.1184 -1200.4

Step:  AIC=-1208.5
candpct ~ state_abbrev + candnumber + quality_cand + qualnumber

                Df Sum of Sq    RSS     AIC
+ total_primary  1  0.164625 4.8222 -1217.0
+ openseat       1  0.138040 4.8487 -1215.3
+ PartyDonors1   1  0.044497 4.9423 -1209.3
+ former_worker  1  0.038822 4.9480 -1208.9
+ dist_income    1  0.037661 4.9491 -1208.9
&lt;none&gt;                       4.9868 -1208.5
+ college        1  0.020276 4.9665 -1207.8
+ cand_party     1  0.013294 4.9735 -1207.3
+ gop            1  0.013294 4.9735 -1207.3

Step:  AIC=-1216.97
candpct ~ state_abbrev + candnumber + quality_cand + qualnumber + 
    total_primary

                Df Sum of Sq    RSS     AIC
+ dist_income    1  0.067333 4.7548 -1219.4
+ openseat       1  0.034245 4.7879 -1217.2
+ college        1  0.032944 4.7892 -1217.1
&lt;none&gt;                       4.8222 -1217.0
+ PartyDonors1   1  0.024123 4.7980 -1216.5
+ former_worker  1  0.020585 4.8016 -1216.3
+ cand_party     1  0.008663 4.8135 -1215.5
+ gop            1  0.008663 4.8135 -1215.5

Step:  AIC=-1219.36
candpct ~ state_abbrev + candnumber + quality_cand + qualnumber + 
    total_primary + dist_income

                Df Sum of Sq    RSS     AIC
+ openseat       1  0.041694 4.7131 -1220.1
+ PartyDonors1   1  0.037690 4.7171 -1219.8
&lt;none&gt;                       4.7548 -1219.4
+ former_worker  1  0.018636 4.7362 -1218.6
+ college        1  0.001894 4.7529 -1217.5
+ cand_party     1  0.001455 4.7534 -1217.5
+ gop            1  0.001455 4.7534 -1217.5

Step:  AIC=-1220.11
candpct ~ state_abbrev + candnumber + quality_cand + qualnumber + 
    total_primary + dist_income + openseat

                Df Sum of Sq    RSS     AIC
+ PartyDonors1   1  0.050633 4.6625 -1221.5
&lt;none&gt;                       4.7131 -1220.1
+ former_worker  1  0.014270 4.6989 -1219.0
+ college        1  0.003095 4.7100 -1218.3
+ cand_party     1  0.000167 4.7130 -1218.1
+ gop            1  0.000167 4.7130 -1218.1

Step:  AIC=-1221.48
candpct ~ state_abbrev + candnumber + quality_cand + qualnumber + 
    total_primary + dist_income + openseat + PartyDonors1

                Df Sum of Sq    RSS     AIC
&lt;none&gt;                       4.6625 -1221.5
+ former_worker  1 0.0151344 4.6474 -1220.5
+ college        1 0.0009597 4.6615 -1219.5
+ cand_party     1 0.0001010 4.6624 -1219.5
+ gop            1 0.0001010 4.6624 -1219.5</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = candpct ~ state_abbrev + candnumber + quality_cand + 
    qualnumber + total_primary + dist_income + openseat + PartyDonors1, 
    data = candidate_final)

Coefficients:
   (Intercept)  state_abbrevAL  state_abbrevAR  state_abbrevAZ  state_abbrevCA  
     1.0030779       0.0428212       0.0671862       0.0016764      -0.0853551  
state_abbrevCO  state_abbrevFL  state_abbrevGA  state_abbrevHI  state_abbrevIA  
     0.0589799       0.0305845       0.0653663       0.0439584      -0.0274889  
state_abbrevIL  state_abbrevIN  state_abbrevKS  state_abbrevKY  state_abbrevMA  
     0.0530875       0.0192071      -0.0412008      -0.0470589       0.0572721  
state_abbrevMD  state_abbrevME  state_abbrevMI  state_abbrevMN  state_abbrevMO  
    -0.1276155       0.0410077       0.0053608       0.1050347       0.0183309  
state_abbrevMS  state_abbrevNC  state_abbrevNE  state_abbrevNJ  state_abbrevNV  
    -0.2368089       0.0188473      -0.0880654       0.0014223       0.0714303  
state_abbrevNY  state_abbrevOH  state_abbrevOK  state_abbrevOR  state_abbrevPA  
    -0.0153163      -0.0350554      -0.1154218      -0.0601408       0.0392801  
state_abbrevRI  state_abbrevSC  state_abbrevTN  state_abbrevTX  state_abbrevUT  
     0.0937451      -0.1558301      -0.0170952       0.0162124       0.0915936  
state_abbrevVA  state_abbrevWA  state_abbrevWI      candnumber    quality_cand  
     0.1157987       0.1451653       0.0275727      -0.1028294       0.0683651  
    qualnumber   total_primary     dist_income        openseat    PartyDonors1  
    -0.0436273       0.0943456      -0.1701731       0.0668427       0.0004865  </code></pre>
</div>
</div>
<p><strong>selected model</strong></p>
<p>lm(formula = candpct ~ candnumber + quality_cand + qualnumber + openseat + dist_income + total_primary, data = candidate_final)</p>
<p>This is the model selected through backward selection. It has the lowest AIC and fewer variables than the best model generated through forward selection.</p>
<p>we also picked the top three variables: candnumber, dist_income, total_primary</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>lmInt <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> candpct <span class="sc">~</span> candnumber <span class="sc">*</span> quality_cand <span class="sc">*</span> qualnumber <span class="sc">*</span> openseat <span class="sc">*</span> dist_income <span class="sc">*</span> total_primary, <span class="at">data =</span> candidate_final)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">linear_reg</span>()<span class="sc">|&gt;</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(candpct <span class="sc">~</span> candnumber <span class="sc">*</span> quality_cand <span class="sc">*</span> qualnumber <span class="sc">*</span> openseat <span class="sc">*</span> </span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>        dist_income <span class="sc">*</span> total_primary, <span class="at">data =</span> candidate_final) <span class="sc">|&gt;</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glance</span>() <span class="sc">|&gt;</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(AIC)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -447.1903</code></pre>
</div>
</div>
<p>conclusion: the interactive multiple linear regression model gave us a worse AIC, -447, which was higher than 1236.62. Therefore, we will keep the original addictive model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>candidate_final <span class="ot">&lt;-</span> candidate_final <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">candnumber2 =</span> <span class="fu">if_else</span>(candnumber <span class="sc">&lt;</span> <span class="dv">4</span>, <span class="st">"small pool of candidates"</span>, </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"large pool of candidates"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">primary2 =</span> <span class="fu">if_else</span>(total_primary <span class="sc">==</span> <span class="fl">0.00000</span>, <span class="st">"NA"</span>, <span class="st">"Other"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>candidate_final <span class="sc">|&gt;</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> dist_income, <span class="at">y =</span> candpct, <span class="at">color =</span> total_primary)) <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_gradient</span>(<span class="at">low =</span> <span class="st">"blue"</span>, <span class="at">high =</span> <span class="st">"orange"</span>, </span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">breaks =</span> </span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.005</span>, <span class="fl">0.1</span>, <span class="fl">0.5</span>, <span class="fl">1.0</span>, <span class="fl">1.5</span>)) <span class="sc">+</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> <span class="fu">subset</span>(candidate_final, primary2 <span class="sc">==</span> <span class="st">"NA"</span>), <span class="at">size =</span> <span class="fl">0.4</span>, </span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">"grey"</span>) <span class="sc">+</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> candnumber2) <span class="sc">+</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"median income of the congressional district (100k)"</span>, </span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"vote share in the primary election (%)"</span>, </span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"campaign funds</span><span class="sc">\n</span><span class="st">&amp; outside spending</span><span class="sc">\n</span><span class="st">(million$)"</span>, </span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Primary predictors to working-class candiates vote share"</span>,</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"among candidates that won the primary elections"</span>, </span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"**points marked grey are those with 0$</span></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a><span class="st">       campaign funds &amp; outside spending as indicated in the dataset"</span></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>       ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/visualization-1.png" class="img-fluid" width="672"></p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>